[package]
name = "der_derive"
version = "0.5.0-pre.1" # Also update html_root_url in lib.rs when bumping this
description = "Custom derive support for the `der` crate's `Choice` and `Sequence` traits"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/der"
repository = "https://github.com/RustCrypto/formats/tree/master/der/derive"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["asn1", "der", "crypto", "itu", "pkcs"]
readme = "README.md"
edition = "2021"
rust-version = "1.56"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
synstructure = "0.12"
