[package]
name = "tls_codec_derive"
version = "0.1.3"
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/tls_codec_derive/"
description = "Derive macros for the tls_codec trait"
readme = "../README.md"
repository = "https://github.com/RustCrypto/formats/tree/master/tls-codec/tls_codec"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["parsing"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
tls_codec = { path = "../tls_codec" }
