[package]
name = "tls_codec"
version = "0.1.5"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
edition = "2018"
documentation = "https://docs.rs/tls_codec/"
description = "A pure Rust implementation of the TLS (de)serialization"
readme = "../README.md"
repository = "https://github.com/RustCrypto/formats/tree/master/tls_codec/tls_codec"

[dependencies]
zeroize = { version = "1.3", features = ["zeroize_derive"] }
tls_codec_derive = { version = "0.1", path = "../tls_codec_derive", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3"

[features]
derive = [ "tls_codec_derive" ]
serde_serialize = [ "serde" ]

[[bench]]
name = "tls_vec"
harness = false
