[package]
name = "spki"
version = "0.4.1" # Also update html_root_url in lib.rs when bumping this
description = """
X.509 Subject Public Key Info (RFC5280) describing public keys as well as their
associated AlgorithmIdentifiers (i.e. OIDs)
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
edition = "2018"
repository = "https://github.com/RustCrypto/formats/tree/master/spki"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["crypto", "x509"]
readme = "README.md"

[dependencies]
der = { version = "0.4", features = ["oid"], path = "../der" }

# Optional dependencies
sha2 = { version = "0.9.8", optional = true, default-features = false }
base64ct = { version = "1", path = "../base64ct", optional = true, default-features = false }

[dev-dependencies]
hex-literal = "0.3"

[features]
std = ["der/std"]
fingerprint = ["sha2"]
alloc = ["base64ct/alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
