[package]
name = "oiddbgen"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.5.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
regex = "1.5.4"
syn = "1.0.86"

[workspace]
members = ["."]
