[package]
name = "x509"
version = "0.0.1" # Also update html_root_url in lib.rs when bumping this
description = """
Pure Rust implementation of the X.509 Public Key Infrastructure Certificate
format as described in RFC 5280
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/RustCrypto/formats/tree/master/x509"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["crypto"]
readme = "README.md"
edition = "2021"
rust-version = "1.56"

[dependencies]
der = { version = "=0.6.0-pre.1", features = ["derive", "alloc"], path = "../der" }
spki = { version = "=0.6.0-pre.0", path = "../spki" }
x501 = { version = "=0.1.0-pre.0", path = "../x501" }

[dev-dependencies]
hex-literal = "0.3"

[features]
alloc = ["der/alloc"]
std = ["der/std"]
pem = ["alloc", "der/pem"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
